### ISSUE TITLE
Change Website Links to new Training video locations

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#100]
I have moved the GenevaERS Training videos from the Sharealedger site to the GenevaTV site.  The website needs to be updated with the following links.

No  | Title  | Old Sharealedger List | New GenevaTV list

1 | GenevaERS Training Module 1: Introduction to Views | https://youtu.be/DtEECBaqIY8 | https://youtu.be/S5xTvEKpQgE
2 | GenevaERS Training Module 2, the Performance Engine Overview | https://youtu.be/WvPRFTnarJ4 | https://youtu.be/HyenKk0EEPc
3 | GenevaERS Training Module 3: I/O Processing and Data Types | https://youtu.be/EtYmO21aQAg | https://youtu.be/kxlNQZbbqr8
4 | GenevaERS Training Module 4: Introduction to Lookups | https://youtu.be/hybmj9n689s | https://youtu.be/8ozHARIYRPg
5 | GenevaERS Training Module 5: Introduction to the Format Phase | https://youtu.be/Z8GVezrgpOc | https://youtu.be/k-UzxMHg0Qs
6 | GenevaERS Training Module 6: Record Filtering | https://youtu.be/2tPNZHH7Yw4 | https://youtu.be/U9LC7yZjeSU
7 | GenevaERS Training Module 7: Column Formulas | https://youtu.be/8IdmRayNK7w | https://youtu.be/ShxoYMFh5dk
8 | GenevaERS Training Module 8: Common Errors | https://youtu.be/ejoI1LFqb9I | https://youtu.be/SgRFBDlNBVU
9 | GenevaERS Training Module 9: Metadata Creation | https://youtu.be/L0PzGKjJHjc | https://youtu.be/3xBxGNQxV1s
10 | GenevaERS Training Module 10: Hardcopy Formatted Output | https://youtu.be/4DjLSxBrlpY | https://youtu.be/SEDizCA8Miw
11 | GenevaERS Training Module 11: Logic Tables and Trace Facility | https://youtu.be/YpUkOtlhCfM | https://youtu.be/DanwFW0tdbo
12 | GenevaERS Training Module 12: Single-Pass Architecture | https://youtu.be/eK2NcFi0xU0 | https://youtu.be/DFjuPHhUEE0
13 | GenevaERS Training Module 13: Single-Step Lookups | https://youtu.be/tHYSp1vSsRE | https://youtu.be/n6hLy74jn4U
14 | GenevaERS Training Module 14: Multi-Step Lookups | https://youtu.be/HEG6pVrP8Ns | https://youtu.be/uRUOEOG0pS0
15 | GenevaERS Training Module 15: Constants and Symbolics in Lookup Key Fields | https://youtu.be/P0pbOkUhbJo | https://youtu.be/3U5bzOG01jM
16 | GenevaERS Training Module 16: Effective-Dated Lookups | https://youtu.be/8pO0Cfpm07A | https://youtu.be/pDqjGWBYzz8
17 | GenevaERS Training Module 17: Format Phase Views | https://youtu.be/is-Bi8hNjpE | https://youtu.be/OPuqFXDkJhc
18 | GenevaERS Training Module 18:  ETS and Other Functions | https://youtu.be/tN7BheDIZx8 | https://youtu.be/iZqKJzyZRko
19 | GenevaERS Training Module 19: Parallel Processing | https://youtu.be/7LXpxUEOaqM | https://youtu.be/6kEljS1Y-CA
20 | GenevaERS Training Module 20: Overview of GenevaERS User-Exit Routines | https://youtu.be/dxruhtCYUCE | https://youtu.be/-pS4zinCiTk
21 | GenevaERS Training Module 21: The WRITE Function | https://youtu.be/nETyrEsPPW8 | https://youtu.be/K9eRO6Pb9PI
22 | GenevaERS Training Module 22: Using Pipes and Token | https://youtu.be/EeUyzT8F6No

The link to the new playlist is  https://youtube.com/playlist?list=PLRiGg1dNn4c3PYNlsNY_0ZuB3frUpUOCq from the old playlist of https://www.youtube.com/playlist?list=PLLP_2tUuSlgabyHvpVQ4S71XTNWroDkbL

**Comment by AOrthVector** [comment]
@KipTwitchell are the videos supposed to be unlisted on YouTube?

**Comment by AOrthVector** [comment]
This has been completed
