### ISSUE TITLE
Please add ma as a contributor to GenvaERS

### ISSUE THREAD

**Issue by gkoppikar** [genevaers/community#101]
Please add me as a contributor to GenevaERS

**Comment by SaPeresi** [comment]
.invite @gkoppikar

**Comment by SaPeresi** [comment]
.invite @gkoppikar

**Comment by SaPeresi** [comment]
.invite @gkoppikar

**Comment by KipTwitchell** [comment]
TSC discussion agrees we should go with the most efficient process possible.

**Comment by SaPeresi** [comment]
This has been updated and tested to the most optimal process we could get.  Closing this item.
