### ISSUE TITLE
Prepare Data for installation validation

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#102]
Team determined on 2/25/21 that use of the training data, which corresponds to the data used in the training videos would be best for use in creating an installation validation process.  

![Screen Shot 2021-02-26 at 2 01 31 PM](https://user-images.githubusercontent.com/29467627/109354526-2be89b00-783b-11eb-8255-c0f86ad85982.png)

Installation will have three parts to installation:
1 - PE execution
2 - Compile execution
3 - WB configuration
Optional Performance Showcase (new Event File and Reference Data, and additional Views)

Part 1:  PE Execution
Things that are required include:
- Create an XMIT File of the required Load Modules.  
- Create a XMIT dataset containing the event files, and the reference files
- Create XMIT file of Views in VDP Format to test installation
- GenevaERS PE Execution JCL  (Reference Phrase, Extract Job)
- Create a JCL member to RECEIVE (the opposite of XMIT) the data (unpack it to z/OS) which JCL member the customer would have to upload and execute (or copy and paste)

Select views to use in the installation validation process:
--MR95 Reference and Extract (with multiple views in one pass, one at least of which does lookups)
--MR95 Extract only (too simple)
--MR95 Extract and MR88 Summarization (Too much)
--All three, Reference, Extract and Summarization

Part 2: Compile
- MR91 Load module
- Compile JCL
- XML

Part 3:  Workbench:
- Workbench load module, and pre-requisites
- Postgres
- Database initialization (xml for import)

Part 4:  Optional Performance
- New Views (VDP and XML in case they want to modify them)
- This will use the VA data to give a larger performance perspective on GenevaERS.  
- Would be good if we could store the VA data somewhere on LF systems.

**Comment by KipTwitchell** [comment]
Decision by team was to focus on Step 3 and Step 4 by themselves.  This is still open because it provides some documentation framework.

**Comment by KipTwitchell** [comment]
@emorrow38, I don't know if the above is useful in our demo documentation.  I sort of doubt it, but thought I would pass to you to decide.  Our Demo really has just two steps, (with an optional performance test step, increasing the data generator data), not the Compile listed in the graph above.  If this isn't useful, let's close this issue.

**Comment by emorrow38** [comment]
I have not been involved in the demo work, so I am perhaps not the best person to ask.  As a more distant person, I would say the above was more useful for us, rather than users.  So I would tend to agree this issue could be closed.
