### ISSUE TITLE
Mission statement for GenevaERS

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/community#103]
In order to complete the LLC for GenevaERS, we need to propose a mission statement for the software.  

I have put something very rough together for this - it need a lot of work.  

Here is a link of popular ones. https://mktoolboxsuite.com/vision-statement-examples/

Here is the possible start:
To enable efficient processing of large amounts of data through the use of established mainframe technology businesses have known for reliability and revitalized decision making without major development migrations.

**Comment by SaPeresi** [comment]
Can people take this and update it or come up with something  more reasonable.

**Comment by SaPeresi** [comment]
Please think about this before next Tuesday so we can finalize at the TSC.  Thanks

**Comment by KipTwitchell** [comment]
Would we also consider map-reduce in some way?

**Comment by KipTwitchell** [comment]
In considering this discussion, I feel that the descriptive words above are about the solution, not the statement of the problem that is being solved.  This statement has rung true for a couple of decades now about GenevaERS solutions.  

The Project mission is to implement the concepts of Business Event based insight systems at scale to radically improve today’s business systems.  Business Event based systems:
-	Produce the most accurate, consistent and transparent outputs, 
-	Respond quickly to changing business needs, 
-	Enable rapid implementation, and
-	Minimize costs over time

**Comment by rhness** [comment]
1)  I think "Respond quickly to changing business needs" kind of implies "Enable rapid implementation," so I don't think we need both.  

2)  I think we should somehow address our product's speed in processing high volumes of data.  

3)  I'm not keen on the way we're using the word "insight."  I think what we're trying to say is that we gain insights by looking at business events as a whole, so then these insights could be called "Business Event-based insights."  But calling the systems that produce them "Business Event-based insight systems" is one too many modifiers for me.  How about just leaving out the word "systems," as in: 
**The Project mission is to implement the concepts of Business Event-based insights at scale to radically improve today’s business systems.** 
or maybe:
**The Project mission is to implement the concepts of Business Event-based Architecture at scale to radically improve today’s business systems.** 

4)  I would add a hyphen to "Event based" to make "Event-based."

**Comment by SaPeresi** [comment]
Efficient processing of billion row files?

**Comment by KipTwitchell** [comment]
So, given feedback above, my proposed current draft is:

The Project mission is to implement Business Event principles at scale to radically improve today’s business systems. Business Event-based systems require processing very significant data volumes, but in exchange they:

- Produce the most accurate, consistent, quickest and transparent outputs,
- Respond quickly to changing business needs, and
- Minimize costs over time

**Comment by emorrow38** [comment]
Here is Eugene's suggested mission:

To radially improve Business Event processing of very significant data volumes to achieve :
    Accurate, fast and transparent output,
    Respond quickly to changing business needs, and
    Minimize costs over time.

**Comment by KipTwitchell** [comment]
To radically improve business systems using Business Event principles while processing significant data volumes to achieve :
- Accurate, fast and transparent output,
- Respond quickly to changing business needs, and
- Minimize costs over time.

**Comment by KipTwitchell** [comment]
I will put the above into https://docs.google.com/document/d/1IX8l-tw8cmaHUlVOalspGdi3b-aXdfok/edit#heading=h.30j0zll

**Comment by KipTwitchell** [comment]
Submitted to OMP
