### ISSUE TITLE
Spark Repo Committer Review

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#104]
Our spark work has progresses enough that we need Neil to have commit access to the Spark Repository.  Sandy and I propose that Neil be added as a committer.  Is there any objection to that?

**Comment by bobmcc9** [comment]
I agree to Neil's nomination to be a committer

**Comment by rhness** [comment]
Fine with me.

**Comment by bobmcc9** [comment]
I agree to this

Regards


Bob McCormack 


 


Senior Software Engineer 
IBM Certified IT Specialist
Infrastructure : IBM Scalable Architect for Financial Reporting 
 


IBM Perth
Level 2 East. The Wentworth Building
300 Murray St, off Raine Lane
Perth WA 6000
 


 



 

Mobile                        0457 617228

 

e-mail:
bobmcc@au1.ibm.com

**Comment by AOrthVector** [comment]
Agree

**Comment by SaPeresi** [comment]
agree

**Comment by KipTwitchell** [comment]
Approved
