### ISSUE TITLE
GitHub Action errors - Invite a new collaborator

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#105]
I recently noticed I was receiving emails about a workflow failing. 

Problem #1, the Invite a new collaborator is failing. Assuming something had changed in the repo being referenced in self_invite.yaml I tried to figure out where to point the yaml file, but ID bdougie has a lot of repos. self_invite.yaml needs to be fixed

Problem #2, the  Invite a new collaborator is being triggered a lot; comments on issues, new issues. Looking at the workflow history, this may have began sometime between 27 days and one month ago. I don't think this workflow should be triggered for all issues and updates

**Comment by SaPeresi** [comment]
Andrea - thanks for pointing this out.  Can you tell me how you know if was running at all?  Where do I look to see this please.

**Comment by AOrthVector** [comment]
I can show you this afternoon

**Comment by AOrthVector** [comment]
@jmertic yes, using a label may be a good trigger

**Comment by SaPeresi** [comment]
The next few comments will determine when the trigger runs. We will then make a fix if necessary. 
OK so closing an issue of add me as contributor triggers the action to run.  It ran without error.

**Comment by SaPeresi** [comment]
adding a comment to this item has triggered the action.

**Comment by SaPeresi** [comment]
We have a new label called Collaborator Add.  I have tested the action that John Mertic changed and it does not execute unless the label is there.  The actions will continue to do the setup and run but skip the add portion.  This will save a much resources as we can.
