### ISSUE TITLE
Add descriptions to two YouTube videos

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#107]
I added the GenevaTV branding to the Jim and Randall videos.
A description needs to be added, and if desired add the location

FYI, I've created a Conversations with Kip playlist which is currently unlisted. I've also added end cards to the three Conversation videos. (Suddenly, the subscribe works properly)

**Comment by KipTwitchell** [comment]
I'm fine with the playlist; I've added the dates and locations and copied the descriptions from what I listed on Conversations with Kip
