### ISSUE TITLE
Update GenevAERS web site with CII Badge sticker

### ISSUE THREAD

**Issue by bobmcc9** [genevaers/community#110]
Folks

a. I am trying to locate who has access to the HTML source for the site https://genevaers.org/

b. I would like to add the CII Badge sticker to that page

c. here is the HTML code to be added

<imgsrc="https://bestpractices.coreinfrastructure.org/projects/4181/badge">

d. it will reflect the current status of this badge which currently is approved and in a GREEN status

many thanx
bob

**Comment by AOrthVector** [comment]
Kip and I have access and can add it to the site

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: bobmcc9 ***@***.***>
Sent: Sunday, March 14, 2021 9:02:51 PM
To: genevaers/community ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [genevaers/community] Update GenevAERS web site with CII Badge sticker (#110)


Folks

a. I am trying to locate who has access to the HTML source for the site https://genevaers.org/

b. I would like to add the CII Badge sticker to that page

c. here is the HTML code to be added

<imgsrc="https://bestpractices.coreinfrastructure. org/projects/4181/badge">

d. it will reflect the current status of this badge which currently is approved and in a GREEN status

many thanx
bob

**Comment by AOrthVector** [comment]
The badge has been added to the sidebar menu on the right side of the page
