### ISSUE TITLE
TSC Infrastructure Agenda Meeting 24 March 2021 

### ISSUE THREAD

**Issue by bobmcc9** [genevaers/community#113]
**MR91 Binary Deliverable**

1.  the mechanics of storing a z/OS load library in GITHUB are understood

- use ADRDSSU  to create a DUMP file from GVBLOAD PDSE
- use TRSMAIN to PACK this file
- store this file (FB LRECL 1024)  into USS from the Git clone directory 
- cp "//'GEBT.PM418075.B1374.GVBLOAD.PACKED'" MR91.bin 
- issue add/commit/push to GITHUB in IBM

2.  the mechanics of deploying a binary file on github  to z/OS are understood
user can download this file using GIT Clone to USS
move from USS to z/OS

- tsocmd " ALLOCATE  DA('GEBT.PM418075.B1374.GVBLOAD.PACK2') DSORG(PS) SPACE(900,200) TRACKS LRECL(1024) BLKSIZE(27648) RECFM(F,B) "
- cp -P "RECFM=FB,LRECL=1024,space=(900,100)" MR91.bin "//'GEBT.PM418075.B1374.GVBLOAD.PACK2'"
- use TRSMAIN to unpack file
- use ADRDSSU to restore orignal PDSE

3. some issues from this deployment are
-  we need to ensure no untoward copyright and licensed materials text is found in the deliverable
-  we require a Prerequisite product on the z/OS system i.e. XML Toolkit. This is a no charge product but can be only obtained from normal IBM sources such as CBPDO/zShop. We have tested running the mR91 load library with the XML Toolkit library and it works. The standard name for the XML Toolkit Library is IXM.V1R11M0.SIXMLOD1
-  some suggestion has been made that the XML System Services may well be supplied within z/OS load libraries, this is being checked 

**PE Deployment**

1. we are currently waiting on curated form of the INVM file which contains all assembler and linkedit values
2. whilst the initial deployment of PE to z/OS will be via GIT clone into USS
3. this will follow a bash script to populate a number of PDSes holding assembler parts, JCL members and empty load library
4. build of the product will most probably be via ISPF tailoring skeletions using INVM as the master. his will product the assemble jobs and linkedit jobs
5. the build jobs are submitted and the product is built
6. deployment of the MR91 binary will then ensue

**Installation Verification**

1. we are think that the best way to verify the PE product is to run the Test Framework
2. at this stage we have deployed two requisites GRADLE and OPEN JDK
3. we have compiled the build.gradle file with a few warnings
4. we now to run the gradle project
5. an issue on how to handle the output HTML file is up for grabs, maybe an automated email is possible

**Java Source Scans** 

1. as an aside we deployed SONAR QUBE to scan workbench java source. This was run on the internal IBM Workbench source. We use the community edition of SONAR QUBE whch did restrict the reportage but the web pages we saw were useful. Can be deployed as a Visual Studio plugin

**Move WorkBench to external Git**

1. waiting on IBM development staff for final tweaks

**Move Test FrameWork to external Git**

1. waiting on development tweaks for this repo

**Move Performance Engine to IBM internal GIt**

1. we have a trial repo present and some work on APACHE 2.0 license updates have been done
2. git clone and some scripting testing are underway

**KANBAN updates**

1. some of the above has been added to our KanBan board at https://jira.openmainframeproject.org/secure/RapidBoard.jspa?rapidView=3&projectKey=GD
2. specifically GD 18 and 24

**Comment by KipTwitchell** [comment]
@bobmcc9 Can we close this issue?  Thanks

**Comment by bobmcc9** [comment]
Closing

**Comment by bobmcc9** [comment]
Closing
