### ISSUE TITLE
We're all - or more of us - are going to need to be commiters to the doc repo

### ISSUE THREAD

**Issue by hammyau** [genevaers/community#115]
I tried to test adding something to the doc repo to see if it showed up in Jira.
I do not have rights to do that.

That will make it hard to add the site generator.

**Comment by hammyau** [comment]
Also need to be owner so I can configure the autolinks -or Admin rights .
See https://stackoverflow.com/questions/29473255/make-jira-links-clickable-in-github

**Comment by AOrthVector** [comment]
I didn't see any GitHub actions setup for the doc repo to add new committers like John setup for the Community repo. If it was setup, we could each request to be automagically added to the docs repo. If someone besides me thinks that's a good idea, I can open an issue to John requesting him to set that up for the docs repo

**Comment by KipTwitchell** [comment]
I added all committers to the Doc Repo
