### ISSUE TITLE
Request ownership status for 2 GenevaERS Developers please

### ISSUE THREAD

**Issue by bobmcc9** [genevaers/community#116]
Folks

a. could a member with OWNER or ADMIN status please

1. add bobmcc9 as an owner please as I need to have access to the SETTINGS tab
2. this will allow me to select AUTO REFERENCES to map to stories in JIRA 
3. could you also assign similar to Ian Cunningham please

**Comment by AOrthVector** [comment]
I assigned to @KipTwitchell as he may have the permissions to do this. Otherwise, we may have to escalate to John

**Comment by KipTwitchell** [comment]
Not sure why your membership was dropped.  I have sent an invite to reinstate.

**Comment by bobmcc9** [comment]
ok many thanx

**Comment by bobmcc9** [comment]
many thanx
