### ISSUE TITLE
Decide on git worklfow

### ISSUE THREAD

**Issue by hammyau** [genevaers/community#120]
Sandy and I had a long chat about git and jira. And git workflows.

I and Jeff are really working on the basis of the Feature Branch Workflow. See document below.
Sandy has experience with the Forked Workflow.

They are really just different ways to achieve the same goal.
Here is a discussion of different types of git workflow. It is worth taking the time to read them and understand them.
https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow 

Then we need to decide as a project which workflow best suites our needs. And at the same time fits in with our use of Jira.

As an aside we probably also need to devise some conventions re naming of branches and formatting of commit comments.
A suggestion would be a branch be named.
<Jira ID> Developer initials and some short description.

Example for the one we were looking at earlier would be
GD-25-IC-initSiteGenerator

Then when we look at the branches they will more readily be more informative.

As a follow on from above given that our Jira is only linked to the GenevaERS repositories I think that may limit the possible workflows? We need the commits to refer to the Jira issues. I'm not sure that will work for a Forked repository?

**Comment by SaPeresi** [comment]
Thanks for the great writeup Ian and for the pushing and testing last night on the sync back connection from github commit to jira issue.  One think I will try to test today is if a forked commit will tie back to jira issues.  This could make a difference in what we decide to do on a workflow and best practices.

**Comment by AOrthVector** [comment]
Action Items - place branching naming convention on GenevaERS How we Work

**Comment by KipTwitchell** [comment]
Do we need this issue still?

**Comment by hammyau** [comment]
No Git Lives....
