### ISSUE TITLE
Choose a order view to be used in import testing and workbench testing.  

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/community#123]
Randall Ness has loaded views to the viacom system.  Of these views he will choose on that Jeff can use for import testing and Ian can use for WB testing.  Randall will attach the XML to this issue for ease of finding it.

**Comment by SaPeresi** [comment]
Neil, Sandy and Randall will discuss the ability to generate a bit of a volume of data for orders to be used as a starting point of the processing and then be broken down to smaller pieces using just the training data.  This should be discussed on Friday working session.

**Comment by rhness** [comment]
Here is a test view XML file.  

[V0000016.txt](https://github.com/genevaers/community/files/6313728/V0000016.txt)

**Comment by neilbeesley** [comment]
Update the view 10651 in WBTR environment 4 to demonstrate summarization of orders by customer -- and to examine MR95 report lookup values if event file is in lookup file order.
It's likely an example we can use for ORDERs, CUSTOMERs and CUSTNAMEs, etc. of this already exists.

**Comment by neilbeesley** [comment]
Jeff you can import the XML file above and then export it, and compare the results.

**Comment by SaPeresi** [comment]
I believe this can be closed. Anyone disagree?

**Comment by KipTwitchell** [comment]
This can be closed via demo system work
