### ISSUE TITLE
What a demonstration of Geneva might look like

### ISSUE THREAD

**Issue by neilbeesley** [genevaers/community#125]
Suggest following view functionality [for Geneva demonstration]:

a) Extract fixed format view with lookup
b) Several extract views with/without lookup
c) Add format phase fixed width fields view with extract phase record aggregation 

Note:
1) these examples will read records from same input event files to demonstrate single pass architecture.
2) There will be multiple input files to demonstrate the multi threaded processing.
3) Need to describe what the EXTRRPT report tells you about each run of the performance engine
4) Demonstration comprises 3 executions: running (a), running (a)+(b), running (a)+(b)+(c) passes of Geneva.

**Comment by neilbeesley** [comment]
Equipment list:
1. executable -- PE and WB.
2. database scripts to postgres
3. documentation with scope of how to run demo -- and what to look at in output report (annotation)
4. JCL to run a pass of PE
5. Sample views in XML format
6. Sample reference and event file(s).
7. Provide help for getting XML (or files files) -- maybe look at SCP as we might find it easier to make use of this

**Comment by KipTwitchell** [comment]
attempted command for postgres configuration:  /usr/local/bin/psql -h 162.241.224.26 -p 5432 -U shareal5_GenevaERSUser1  -v dbname=shareal5_GenevaERS_training -v schemaV=gendev -f runall.sql

**Comment by SaPeresi** [comment]
View number 10687 in env 4 of training.

Changes - add multiplication of quantity to price to get total for line item.
Aggregate that amount.

View 10682 (no mr88)
Change view to have order item as the event.
connect to order to get customer id 

New View with single thread and multi thread. 
orderitem
lookups to order for customer id, using customer id get customer name from customer name with effective date file - effective dated lookup. 
selection criteria on columns for range of year's dates.  column 1 this year, column 2 last year, column 3 previous years, column 4 itd.  
order by customer id, customer name
Sum customer id, customer name

New view 
same view as above 
changing sum on customer id drop customer lookup. 

Stretch goal of:
using customer begin date to calculate and show customer life time value.  
sort by value range and customer id -  value of customer (requires MR88) length of time where sort key is calculation of itd purchase - sort by value, 
use ranges of values for sort key to be more meaningful.  >10,000, 5000 to 10,000 etc

Again based on customer being a customer range of 3 years , 2 years, 1 year and value of the customer.

**Comment by neilbeesley** [comment]
Discussion with Jeff:

Is the lookup and/or data for customer name with effective date a realistic thing to show in the demo -- see above ?

Is it possible to think of better effective date look-ups the would be more meaningful.

**Comment by rhness** [comment]
I think a more meaningful example would be Customer Address.  Your customer's address may change based on an effective date range and this could affect which salesman gets credit for a commission, what rates are in effect, and so on.

**Comment by jhornert** [comment]
I was thinking the 'Item' file would just contain the Product Id and Description. Then have an 'Item Price' file that would contain the Product (Item) Id, Price, Start Effective Date and End Effective Date. This would be the price of the item on specific effective dates as item prices can/will change over time. 

Verify Order Total Cost matches the prices of the items on the order for the specific date. Summary view. The 'Item' file is the event file. Lookup to the 'Order' file with the Order Id to get the Order Date. Then lookup to the 'Item Price' file with the Order Date as the effective date to get the item price.  Summarize view item prices by Order Id. Include the Order Total to verify the totals match. 

Maybe we could walk through how Randall's idea to see what would be required to get it to work.

**Comment by neilbeesley** [comment]
Fridays discussion with Sandy concerning possible demo for effective dates.

1) New view_A to run through order item event file. Lookup to order to get order date. Write to a pipe or a token

2) New view_B to read token and do effective date lookup to customer address to produce columns by state, ordered by customer ID [detail]

3) New view_C to read token and do effective date lookup to customer address to produce columns by state, ordered by customer ID, grouped by date year [aggregated]

**Comment by KipTwitchell** [comment]
This text might be used to update the demo system documentation.

**Comment by emorrow38** [comment]
I am again perhaps not the best person to comment on this issue as I have not been involved in the demo a lot.  As a more distant person, I agree this looks like early discussions of the demo and is no longer useful as the demo has been fully developed now.  

I think we can close this issue.
