### ISSUE TITLE
TSC Infrastructure Meeting Minutes 26 May 2021

### ISSUE THREAD

**Issue by bobmcc9** [genevaers/community#134]
infrastructure agenda

**Comment by bobmcc9** [comment]
**### SAFR Production Binary Deliverable to GIT**

    Kip asked about RM issues in this license.md Bobmcc to chase up

MR91 Binary Deliverable
  
    as source for this deliverable will not reside in GIT only a binary file, we need to perform a special build on KANPLEX     to ensure correct version release number
    bobmcc advised a bespoke build for this with a specific VRM needed

Performance Engine sans CPP code Build

    Randall is now leading the design on this task

Move Performance Engine to IBM Internal GITHUB

    currently waiting on a INVM examination for open source shipment
    also an analysis of PE source code has shown up a number of abnormalities that Randall is researching

Installation Verification

    Plan here is to deploy the testsuite
    on USS on Kanplex we performed a GIT clone of the Test Framework repo
    we deployed GRADLE software onto USS
    Using GRADLE we ran the Test Framework as a pure java application to perform all the tests
    We ran Apache Rat on this repo to add additional license text

Java Source Scans

    some training exist to show SAFR staff to use SONAR QUbe
    We use the community edition of SONAR QUBE

Move WorkBench to external Git

    waiting on IBM development staff for final tweaks

Move Test FrameWork to external Git

    waiting on development tweaks for this repo

**Comment by KipTwitchell** [comment]
Meeting complete.
