### ISSUE TITLE
FTP download option with GenevaERS.org Web site

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#138]
GitHub has a 100 Meg per file limit which our load modules exceed.  Is it possible to have an ftp site associated with GenevaERS.org website?

**Comment by AOrthVector** [comment]
I suspect we're going to get a no for the same reasons you couldn't do it with your hosting. Before I open a ticket to ask, what other options have been researched? 
Also, what is the exact file size?

**Comment by rhness** [comment]
Our current load library is 120 MB, so let's ask for 150 MB just to give us a little extra buffer.

**Comment by KipTwitchell** [comment]
Our "release" on Github solves this problem.  No other work needed.
