### ISSUE TITLE
Link to OMP LLC Charter in Readme

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#148]
The following should be included in our Readme somewhere:  https://github.com/openmainframeproject/foundation/blob/main/project_charters/genevaers_charter.pdf

**Comment by emorrow38** [comment]
Done - see "Charter' link on Home page.

**Comment by emorrow38** [comment]
Sorry, I put it on the the website for "Demo documentation'.  I will also put it in the Readme.

**Comment by emorrow38** [comment]
The Readme points to the "Demo Documentation' website, so there is no need to change the Readme.  The charter is clearly marked on the website now.
