### ISSUE TITLE
Give Andrea Access to Zoom Admin

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#16]
@AOrthVector @jmertic , how do I start zoom so that it is recorded on the server, rather than my local machine? Also, can I (or you) share the zoom credentials with Andrea so that she can be my backup for the meetings?

**Comment by jmertic** [comment]
@AOrthVector I've sent you an invite to LastPass - when you get it let me know.

**Comment by AOrthVector** [comment]
This is complete now. The shared credentials are in Andrea's LastPass
