### ISSUE TITLE
blog updates

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#17]
@AOrthVector , I think it would be good to get the slides from Randall to perhaps post in the meetings, and I think we should do an updated blog "activity" post on GenevaERS.org. It could include (1) links to the TSC meetings minutes and videos for the TAC and the two TSC meetings, (2) and Randall's slides, (3) and the logo results. We can also update the site with the new logos.

**Comment by AOrthVector** [comment]
Via GitHubs advanced search, I pasted the created URL to to add a link to the TSC minutes. I'm not in love with this solution, but I don't want to do something manual either

However, I couldn't build a search URL for the mp4s because GitHubs advanced search only wants to search on code

**Comment by AOrthVector** [comment]
Can someone give me a blurb on why having a logo is an important step in the project's journey. My creativity so far extends to "yay! we have a logo" which probably isn't enough

@KipTwitchell @rhness

**Comment by KipTwitchell** [comment]
ah, @AOrthVector I just found this link; there is much to do here, from the TSC checklist.  https://github.com/openmainframeproject/foundation/issues/new/choose

**Comment by AOrthVector** [comment]
Out of this list, I think the only applicable items are the latest version of Randall's slides and updating the website with links to the TSC meeting assets and TAC

**Comment by KipTwitchell** [comment]
Issues resolved.
