### ISSUE TITLE
Proposed genevaers repository names

### ISSUE THREAD

**Issue by ghannington** [genevaers/Community#175]
The repositories should have names that make it clear what is contained in them.
It has previously been proposed we use Train-Case for repositories.
This spreadsheet contains some proposals. Comments please.
[Open source repo names.xlsx](https://github.com/genevaers/community/files/9450386/Open.source.repo.names.xlsx)

**Comment by emorrow38** [comment]
Very sensible ideas - let's use them all.

**Comment by AOrthVector** [comment]
Names look good

**Comment by AOrthVector** [comment]
I've made the updates
