### ISSUE TITLE
High priority scanning finding

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/Community#177]
Kip, can you and Ian take a look at this? 

Below is what John sent me

> Here are the results from the February 2023 license scan of the GenevaERS project.  The scan was performed using the Linux Foundation Fossology server.  Licenses and copyrights were examined.
> 
> The key findings and license summary can be found in the HTML report, the list of files in the spreadsheet, and also find the SPDX file listed below:
> 
> WARNING:  There is a high priority finding that must be addressed, see the report for the details and the files affected.  Here is the comment from the report:
> 
> These files are under EPL-1.0, and you have added the Apache-2.0 license - this is not allowed, you can't re-license this code unless the authors/copyright holder gives permission. You either need to remove these files from your repo, or update the file headers and remove the additional copyright and Apache license statements. If you have permission to re-license the code under Apache-2.0, remove the EPL-1.0 license statements. If you keep this code under EPL-1.0, be sure to add a reference to it in your NOTICE file.
> 
> REPORTS:
> 
> omp/genevaers, code pulled 2023-02-11
>   - report: https://lfscanning.org/reports/omp/genevaers-2023-02-11-7f0c716e-d663-4ac6-a822-60bac62e6ead.html
>   - xlsx:   https://lfscanning.org/reports/omp/genevaers-2023-02-11-7f0c716e-d663-4ac6-a822-60bac62e6ead.xlsx
>   - spdx:   https://github.com/lfscanning/spdx-omp/tree/master/genevaers/2023-02/genevaers-2023-02-11.spdx
> 
> Please feel free to contact me with any questions about the scan results.  Be sure to reply to me directly as I may not get an email sent directly to the distribution list.
> 
> Thanks, Jeff
> 
> Jeff Shapiro
> 408-910-7792
> [jshapiro@linuxfoundation.org](mailto:jshapiro@linuxfoundation.org)

**Comment by hammyau** [comment]
Thanks Andrea, we'll sort it.

**Comment by bobmcc9** [comment]
I updated 102 parts where we had EPL 2.0 and Apache 2.0 licenses present
This was originally due to a RAT update process on Nebula parts which had EPL 2.0 present

The change has been pushed into the main branch via the merge process

**Comment by bobmcc9** [comment]
Oops  prior comment EPL 2.0  should be EPL 1.0

**Comment by bobmcc9** [comment]
will update NOTICE file on Monday

**Comment by bobmcc9** [comment]
NOTICE file has an EPL 1.0 entry

**Comment by AOrthVector** [comment]
this was taken care of, but forgot to close the issue
