### ISSUE TITLE
Joining Community Guide

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#18]
Sandy, just noting an issue with the work you are doing on the Getting Started Guide.

**Comment by SaPeresi** [comment]
Sandy to check how review is progressing on Joining Guide.

**Comment by SaPeresi** [comment]
Document is completed we just need to put it somewhere it can be accessed on GenevaERS.org and somewhere is GitHub.  Thoughts?

**Comment by 00fatima00** [comment]
The Getting Started Guide / On Boarding document has been completed by Sandy. Instructions are on point, self explanatory and easy to follow

**Comment by SaPeresi** [comment]
Document has been added to GenevaERS.org and I am working on getting it into the Community repo.

**Comment by KipTwitchell** [comment]
Sandy to add to repo.

**Comment by SaPeresi** [comment]
Uploaded to community repo.
