### ISSUE TITLE
work jdbc issue

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#19]
the workbench requires jdbc access.  Here are the approaches we agreed could be taken on this issue:

- Gain permission to use the DB2 Connect jdbc driver.  @Rhness working this.
- Find an open source equivalent to that driver.  @SaPeresi  working this.
- Use a DB2 local install.  @bobmcc9 is working this.
- Convert WB to not require DB2 and use another open source database.  This is on hold.
- version 5 new WB paradigm will also remove this problem.

**Comment by KipTwitchell** [comment]
Can this be closed?  Discuss at TSC.

**Comment by rhness** [comment]
This can be closed.  We implemented the item that says, "Convert WB to not require DB2 and use another open source database."

**Comment by KipTwitchell** [comment]
Issue is resolved.
