### ISSUE TITLE
High priority scan finding

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/Community#234]
The below looks similar to issue [Issue 177](https://github.com/genevaers/Community/issues/177)

On Thu, Nov 2, 2023 at 5:35 AM Jeff Shapiro <[jshapiro@linuxfoundation.org](mailto:jshapiro@linuxfoundation.org)> wrote:
Hi Team,

Here are the results from the October 2023 license scan of the GenevaERS project.  The scan was performed using the Linux Foundation Fossology server.  Licenses and copyrights were examined.

The key findings (if any) and license summary can be found in the HTML report, the list of files in the spreadsheet, and also find the SPDX file listed below:

NOTE:  There are high priority key findings, please address these as soon as possible:

Finding #1
Priority: High
These files are under EPL-1.0, and you have added the Apache-2.0 license - this is not allowed, you can't re-license this code unless the authors/copyright holder gives permission. You either need to remove these files from your repo, or update the file headers and remove the additional copyright and Apache license statements. If you have permission to re-license the code under Apache-2.0, remove the EPL-1.0 license statements. If you keep this code under EPL-1.0, be sure to add a reference to it in your NOTICE file.
53 files

REPORTS:

omp/genevaers, code pulled 2023-10-11
  - report: https://lfscanning.org/reports/omp/genevaers-2023-10-11-2bb4c013-c0c7-4143-8176-c539f3e21930.html
  - xlsx:   https://lfscanning.org/reports/omp/genevaers-2023-10-11-2bb4c013-c0c7-4143-8176-c539f3e21930.xlsx
  - spdx:   https://github.com/lfscanning/spdx-omp/tree/master/genevaers/2023-10/genevaers-2023-10-11.spdx

**Comment by bobmcc9** [comment]
Folks
a. this may be caused by scanning genevaers.zip file we had under a RELEASE in the Workbench repo. This zip file had files that mapped to the criteria mentioned in this issue

b. this release and its TAG have been deleted

c. the other two RELEASES we have in this Repo are Ok
