### ISSUE TITLE
I don't think I have the permissions to approve a pull request

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#29]
When Kip asked me to approve a pull request for him, the only option I had was to comment. I was looking out on the GitHub documentation, and I did not have the options listed in the documentation on the page called Approving a pull request with required reviews

**Comment by KipTwitchell** [comment]
@jmertic Could you look at this?

**Comment by jmertic** [comment]
Try now - looks like someone you weren't added as a committer on this repo.

**Comment by AOrthVector** [comment]
It worked!
