### ISSUE TITLE
What are all the meetings we have a cadence for?

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#30]
I want to "one stop shop" the meetings we have instead of having multiple menu drop downs.
We have the following meeting I'm aware of:

- TSC
- Daily status

@KipTwitchell @rhness

**Comment by KipTwitchell** [comment]
We just added 
- Monthly Infrastructure Meeting (30 min), following 4th Tuesday (US time) TSC meeting.

**Comment by AOrthVector** [comment]
Is there a permalink for the infrastructure meeting?

**Comment by KipTwitchell** [comment]
Need to make an entry for it.  Also, I think you and I need to have a short session the week before TSC meetings to agree on agenda and make updates to the calendar invite for each meeting.
