### ISSUE TITLE
Release and CI/Build requirements 

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#31]
In the interest of ticking [this list off](https://github.com/genevaers/community/tree/master/tsc), we need to define two items and what is required to complete them:

- Release methodology defined ( RELEASE.md )
- CI/build environment

It would be nice if we could tick these off by the end of next week before the OMP conference.

(FYI, we have determined that "CII Badge achieved ( apply at https://bestpractices.coreinfrastructure.org/en )" is not a project initiation task, but incubation graduation task, so we will be working that in monthly infrastructure GenevaERS meetings, to be scheduled by @rhness but likely being the 4th Tuesday of the Month (us time) after the TSC meeting).

**Comment by AOrthVector** [comment]
Looking at the documentation and examples from [this page](https://bestpractices.coreinfrastructure.org/en), my suggestion is that we have a project board to define what is needed to satisfy the CI/build and what skillsets we lack or have to achieve passing

**Comment by bobmcc9** [comment]
- Andrea's comment has merit
- we have multiple pieces in play here

- GUI (V4 and V5 plus variants
- utilty program(s)
- manframe portion

**Comment by AOrthVector** [comment]
Bob has created the Release document and this issue is not necessary to track remaining work towards the CII Badge
