### ISSUE TITLE
Wordpress theme potential future issues

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#33]
I was looking up to see of the theme being used on the GenevaERS supported features introduced in Wordpress 5. When I searched for the Dara theme on the Wordpress.org website, it had this message

> This theme hasn’t been updated in over 2 years. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

I would like to add it to my list of things to do to switch to a theme that is being maintained

**Comment by KipTwitchell** [comment]
I'm fine with that.  I spent a total of perhaps 30 minutes choosing the one that was used.

**Comment by AOrthVector** [comment]
Changed the theme, and tweaked the colors to match the logo. Made a couple small changes in the sidebar so the "follow" is prominently at the top of the sidebar
