### ISSUE TITLE
Good first issue - Research Izoda 

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/community#44]
It is necessary to do some research on the Izoda product to ensure that the project makes use of whatever is available to be used.  The purpose of this issue is to get a summary of what the product can do and how it will be useful to GenevaERS project.

**Comment by KipTwitchell** [comment]
I am working this by joining the Apache Spark email group to listen in on their conversation.

**Comment by KipTwitchell** [comment]
I think we have completed this work.
