### ISSUE TITLE
Search for GenevaERS on GitHub

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/community#47]
When I do a search for GenevaERS on GitHub I only get 2 repos.  Even if I sign in, I still only have two.  The GVBLIB and IBMSAFR.  When I click on GenevaERS in the heading I see all the repos.  Is there something wrong in permissions.

**Comment by AOrthVector** [comment]
I've found the easiest way to see all the GenevaERS repos is to click on the genevaers breadcrumb at the top left when I'm in community. When I do a search, I have results similar to you. Maybe the search feature doesn't search well on the organization name

**Comment by SaPeresi** [comment]
To be discussed along with @jmertic along with several others. Discussion to include if possible @AOrthVector and @SaPeresi

**Comment by KipTwitchell** [comment]
Sent Github feedback asking for where to post issue.

**Comment by KipTwitchell** [comment]
Working as designed (even though that seems very inadequate to the purpose involved.)
