### ISSUE TITLE
Please add me to genevaers organization

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#5]
Unless you want project boards for each repository, than you'd have to do your admin magic specific to the repos

**Comment by AOrthVector** [comment]
I've been digging through the GitHub [documentation ](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/project-board-permissions-for-an-organization)I think Sandy and I would need to have organization permissions of project admin.

Also, I found [this ](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams)on setting up teams and how permissions work, if we're not currently set up teams, it's a permissions approach to think about.

**Comment by KipTwitchell** [comment]
I think some of this Is waiting on the TSC meeting.  Would you be willing to take minutes of the TSC meeting next week?  It will also be recorded.

**Comment by AOrthVector** [comment]
Sure

**Comment by KipTwitchell** [comment]
So John, as discussed in slack, please:
1-merge the PR for the committer doc that I published (https://github.com/genevaers/community/pull/9)
2-Create the resources and doc repos
3-Add the following members to the GenevaERS project:  elanadunn, AOrthVector, SaPeresi, rhness
4-grant committer accesses based upon this table: https://github.com/genevaers/community/blob/committer-updates/COMMITTERS.csv

**Comment by jmertic** [comment]
Hey @KipTwitchell!

- Added a comment on #9 to make some adjustments before merging ( once that's done 1,3,4 are unblocked )
- Repos are created ( handles 2 )

**Comment by KipTwitchell** [comment]
complete
