### ISSUE TITLE
Review Zoom sharing options

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#50]
Recordings and transcripts from TSC are still giving the no permission message. Per Google, a fix may be to adjust the Share this recording option to be public.

**Comment by SaPeresi** [comment]
To be discussed along with @jmertic along with several others. Discussion to include if possible @AOrthVector and @SaPeresi

**Comment by AOrthVector** [comment]
No longer applicable as video files are being stored in a Google drive

**Comment by KipTwitchell** [comment]
I think we will live with the options provided to us.
