### ISSUE TITLE
TSC Meeting

### ISSUE THREAD

**Issue by bobmcc9** [genevaers/community#53]
Jeff and I came in for the scheduled TSC meeting  today

_When:
Tuesday, 6 October 2020, 8:00pm to 9:00pm
(GMT-05:00) America/Chicago
Where:
Join Zoom Meeting https://zoom.us/j/94966206199  Meeting ID: 949 6620 6199
Organizer: Kip Twitchell kip.twitchell@us.ibm.com 1 (720) 395-5926‬ 
Details:
Open Mainframe Project Community is inviting you to a scheduled Zoom meeting._  

a.  mayhaps the call schedule has changed

b. could a new schedule be published

many thanx
bob Mccormack

**Comment by SaPeresi** [comment]
To be discussed along with @jmertic along with several others. Discussion to include if possible @AOrthVector and @SaPeresi

**Comment by AOrthVector** [comment]
The bot is not smart enough to schedule 2nd and 4th Tuesdays of a month so John changed how the bot worked so it can be kicked off on demand.
