### ISSUE TITLE
Gimme those links for the right side of the wordpress site

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#6]
And the necessary access please

**Comment by KipTwitchell** [comment]
Give me your e-mail address.  We'll begin by making you a contributor.  (also, don't see your name here yet, needed for you to join the TSC meeting next week).  genevaers-discussion+subscribe@lists.openmainframeproject.org

**Comment by AOrthVector** [comment]
Odd, I thought I had subscribed, I'll double check that. 
spookykitty93@outlook.com

**Comment by KipTwitchell** [comment]
author authority given.
