### ISSUE TITLE
Check Randall's permissions - does he have write access?

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#65]
I'm late on this. There is a pull request out there that I asked Randall to approve while Kip was not available. I watched Randall approve it. But he did not have the capability to use the Update Branch version, nor does it look like GitHub accepted his approval.

We need to get this pull request cleared and we need to get something more flexible for who can give permissions. This would not scale

**Comment by jmertic** [comment]
Looking at https://github.com/genevaers/community/blob/master/COMMITTERS.csv, he appears to be a committer on everything but the Community repo. If there intention is that he should, then feel free to make a commit to that file with the change and the vote can happen.

**Comment by AOrthVector** [comment]
The committers file was updated in the TSC branch from 11/10/2020. As soon as the pull request is approved the file will reflect that Randall should be a committer in Community
