### ISSUE TITLE
Requesting access to the project

### ISSUE THREAD

**Issue by neilbeesley** [genevaers/community#66]
Joined email list and would like to be accepted to the project.

**Comment by SaPeresi** [comment]
.invite @neilbeesley

**Comment by SaPeresi** [comment]
.invite@neilbeesley

**Comment by KipTwitchell** [comment]
.invite @neilbeesley

**Comment by jmertic** [comment]
.invite @jmertic

**Comment by jmertic** [comment]
.invite=@jmertic

**Comment by jmertic** [comment]
.invite @jmertic

**Comment by jmertic** [comment]
.invite @jmertic

**Comment by jmertic** [comment]
.invite @jmertic

**Comment by jmertic** [comment]
.invite @neilbeesley

**Comment by jmertic** [comment]
.invite @neilbeesley

**Comment by jmertic** [comment]
.invite @neilbeesley

**Comment by SaPeresi** [comment]
Neil is now a member of the team - we can close this issue.
