### ISSUE TITLE
Agenda TSC Meeting Tuesday 11/10/2020

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#68]
## Agenda
Issues
* Access requests #66 and #67
* Issue #64 - John's suggestions
* If time other open issues

### Pull Request
* Andrea needs a committer to approve and merge

### Spark Update - Randall

**Comment by rhness** [comment]
Suggestions for additions: 
Workbench Update - Ian 
Performance Engine Update - Gill 
Infrastructure Update - Bob

**Comment by AOrthVector** [comment]
added

**Comment by bobmcc9** [comment]
Infrastructure

- GIT to RTC synchronisation

- GIT Clone on VICOM

- GVBLIB Merge done and we wait on a SPM PTF for HLASM Toolkit

- Use of SPARK

- Spacer on VICOM and World Data

**Comment by AOrthVector** [comment]
add infrastructure items

**Comment by AOrthVector** [comment]
Meeting has been held and minutes are waiting for the pull request to be approved
