### ISSUE TITLE
Update Wikipedia

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#71]
This issue stems from an update during the 11/10/2020 TSC meeting. Looks like the GenevaERS re-direct should be removed allowing that page to be updated independently of the IBM SAFR wikipedia change.

**Comment by KipTwitchell** [comment]
I have tracked changes in this Word document from the current SAFR entry to update it for GenevaERS.  I took the time to find as many external footnote references as I could to overcome the concerns of general applicability.  I think the links will probably stop that problem.
 
The tone of a Wikipedia entry has to NOT be marketing related in any way.  I also attempted to use as much of the current entry as I could.  I am sure the editors look for places people take one entry and try to turn it into something completely different.  So some consistency is important.
 
To that end, I have left in the title the SAFR name.  In perhaps a year or two, if there are no other comments from editors (I suspect this edit will trigger some editor looking at it, but I can take months before they do so), then I think at some point that part of the title could be edited out.  But I would not do it now.  (The editor reading it might do it as the text makes it clear it is not being used any longer which would be the best case).
 
I did think there are a couple of things that could be added to it perhaps:
- If there were some good performance statistics, that would probably be a good add, but there won't be some externally validated source for those, so might not make it
- It could use the client listed in the museum slide, to give a sense of the industry breath, but again, no external validation for that data. https://genevaers.org/the-museum/

[Wikipedia Updates SMP.docx](https://github.com/genevaers/community/files/6125866/Wikipedia.Updates.SMP.docx)

**Comment by AOrthVector** [comment]
I think this is a good first try and making updates and not triggering a review. I think we should try it as is

**Comment by rhness** [comment]
Here are my edits.  There were discussed in the 2021-03-15 GenevaERS scrum meeting.  
[Wikipedia Updates SMP (with RHN edits).docx](https://github.com/genevaers/community/files/6144611/Wikipedia.Updates.SMP.with.RHN.edits.docx)

**Comment by KipTwitchell** [comment]
Updated.  Cannot edit the title of a wikipedia entry:  https://en.wikipedia.org/wiki/IBM_Scalable_Architecture_for_Financial_Reporting

**Comment by KipTwitchell** [comment]
Wikipedia is updated.
