### ISSUE TITLE
Related to issue #71 - update the website with information regarding the open source nature of GenevaERS

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#72]
This also comes from an issue discussed during the TSC meeting on 11/10/2020

**Comment by KipTwitchell** [comment]
Andrea, is this still active?  Should we discuss on TSC next week?

**Comment by AOrthVector** [comment]
I'm going to roll this into this JIRA item
https://jira.openmainframeproject.org/secure/RapidBoard.jspa?rapidView=3&projectKey=GD&view=detail&selectedIssue=GD-14
