### ISSUE TITLE
Future dated changes to be made - wish list items

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/Community#77]
During our meetings, we have some items come up that would be nice to have or wish list items.  Where do we wish to store those? Items such as enhancing the compiler to allow a lookup to reference a previous column - so that you can change the value in a column in the view and then do a lookup with that changed value.

**Comment by hammyau** [comment]
I would have thought we should keep them in here. Github as issues for the various products.

**Comment by AOrthVector** [comment]
Yes on GitHub, but I dearly wish GitHub’s board were as functional as GitLab’s. This type of thing would be much easier to track and prioritized
