### ISSUE TITLE
Project / Kanban board requirements and possible solutions

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/Community#78]
The project / kanban board, and issue functionality in GitHub is very rudimentary compared to other solutions.
In this issue thread, we can list requirements, optional features and possible solutions

**Comment by AOrthVector** [comment]
Requirements:

- Scalable; must support the current # of people working on GenevaERS along with possible future growth
- Free / low cost
- Tags / labels including ability to apply multiple tabs
- Multiple project / kanban boards
- Supports Agile
- Allows for template creation for new items - consistency of entry and a time saver
- Prioritization
- Ability to customize boards

- Project / kanban boards built dynamically based off of tags
- Supports milestones / Features and Epics
- Automatic analytics

**Comment by KipTwitchell** [comment]
Discuss what we will do if Jira can't be connected automatically.

**Comment by hammyau** [comment]
It has to be easy to use and directly linked to the issues in Github. So issues can be created/tracked in either system.
And traceable in that for any given issue we can see what changes were made. And why.

**Comment by SaPeresi** [comment]
Have received another communication from Linux Foundation - they are looking into the connection.

When we write user stories for the kanban board they should be in the format of:
As a < type of user >, I want < some goal > so that < some reason >.

**Comment by SaPeresi** [comment]
I have used what we learned last night in the TSC to connect all the genevaers repositories to our GD development board.  I am unclear how to test that it is accurate or a functionality.  Anyone have any ideas?

**Comment by SaPeresi** [comment]
Given the question and the fact that the sync between Jira and Github for issues is a paid product, I put together a flow of how the work could progress.  Please comment and suggest.  I am thinking this might help other joining the team and clear up any questions.  

![image](https://user-images.githubusercontent.com/67481368/113063510-6ec3c880-9183-11eb-8c9e-0f602fb4e0ae.png)
