### ISSUE TITLE
TSC Agenda 22 Dec 2020

### ISSUE THREAD

**Issue by bobmcc9** [genevaers/community#81]
### **Meeting Agenda** meeting cancelled....

  

-   use of IBM Code Scan and Reporting Tool (CSAR) - base line taken and report shipped to IBM SAFR Manager. 
     
-     examine use of IBM AppScan (cloud and on prem). the cloud variant (ASOC) has a white Source back end, Tried Appscan as    
       but it wanted all parts in one location i.e. source plus built product plus any referenced jars. This proved a little difficult.
 
-     no time lines for project board for CII Badge but we have been reminded we still have not completed the Badge requirements and will receive reminders every 30 days
 
-     PTF for structured macros changes on HLASM TOOLKIT has been issued, so when we move performance engine to git
       we can strip out structured macros.

-     developed a spreadsheet (IBM internal) on how to move Workbench into Git. First step is to create a new stream in RTC stripping out all the parts not needed for GIT  . We did deploy  ScanCode Toolkit against the IBM production source for workbench and stored the html reports. Will rerun again the Workbench on the iBM git when we place it there. Did find that RAT for APACHE will add copyright strings
 
-     FY11REQ financial data was modified as financial data was changed from simple numeric data to packed decimal S(11)V2
 
-     No news about SPARK on z/OS availability

**Comment by KipTwitchell** [comment]
Did we get the minutes done here as well, and can we close?

**Comment by bobmcc9** [comment]
My diary shows no minutes by me for that date but I think this may have been a cancelled meeting due to XMAS period

**Comment by bobmcc9** [comment]
Closing
