### ISSUE TITLE
TSC Infrastructure Meeting  26 January 2021

### ISSUE THREAD

**Issue by bobmcc9** [genevaers/community#89]
- APACHE RAT

    deployed against a putative Test framework report on IBM's GHE to update JAVA parts

- SAST

    plan to run IBM Code Scan and Reporting Tool (CSAR) - when WorkBench is moved to github/IBM

- CII Badge

    need to get a DAST

- Planning

    developed a spreadsheet (IBM internal) on how to move Perfromance Engine into Git. Progress with copyright testing shows some effort is to be required

- Spark

PAX file deployed on KANPLEX

WorkBench into IBM GitHub

    currently now deployed into the IBM GHE

**Comment by KipTwitchell** [comment]
Bob, did this get converted to meeting minutes?  Can we close.

**Comment by bobmcc9** [comment]
APACHE RAT

    deployed against a putative Test framework report on IBM's GHE to update JAVA parts. Rat has a weakness with XML and z/OS  source files - they are ignored. It was a good test as we need to branch, update, commit, push and then merge

    SAST

    plan to run IBM Code Scan and Reporting Tool (CSAR) - when WorkBench is moved to github/IBM. This has been performed

    CII Badge

    need to get a DAST - still looking at candidates

    Planning

    developed a spreadsheet (IBM internal) on how to move Perforance Engine into Git. Progress with copyright testing shows some effort is to be required - has been done

    Spark

PAX file deployed on KANPLEX and Neil has been advised

WorkBench into IBM GitHub - stable and being actively worked by Ian.

**Comment by bobmcc9** [comment]
Closing issue

**Comment by bobmcc9** [comment]
Agenda converted to Minutes
