### ISSUE TITLE
Design Decisions are documented here

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/Community#90]
This should be used an a repository to capture design decisions until such time as we have a better way.  Each comment should be another decision.

**Comment by SaPeresi** [comment]
Workbench help inclusion:  It was decided that the help currently in the workbench would go directly to a website as opposed to internally in the build.  This will work toward allowing the product to facilitate multiple platforms.  Decision made at TSC on 1/26/21

**Comment by SaPeresi** [comment]
It will be required to type in database password instead of having it stored. Disable Geneva password prompt for environment security.  Issue #99,

**Comment by KipTwitchell** [comment]
@SaPeresi, I think it would be better to document in other ways than in this issue, like what we have done with the activity pages on the website.  Are you OK with closing this?
