### ISSUE TITLE
Project Update Blog Due end of Feb

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#92]
From Mae:  2 - I’m reaching out to all of the project leads and asking for a blog that will give our readers a look into where your project is going in 2021. It can be as long as you’d like as long as it gives a quick overview of the project, a few milestones for this year and then a summary of how to get involved. Basically, a lot of the details that you just presented in the marketing meeting. :) 

lets schedule your longer new GenevaERS blog a few weeks after that. How about March 3? Does that give you enough time to get your thoughts together? I would just need your draft by Feb. 26.

**Comment by AOrthVector** [comment]
OMP has published the post https://www.openmainframeproject.org/blog/2021/03/03/genevaers-milestones-goals-and-more
