### ISSUE TITLE
Discussion item - name change suggestion for the commercial version of GenevaERS

### ISSUE THREAD

**Issue by AOrthVector** [genevaers/community#94]
Low priority but I needed to capture before it slipped out of my head

I've been poking around various websites for open source software. There are some applications that are similar to GenevaERS in the context they have an open source option and a commercial option. One pattern I see is that the commercial version name is appended with the word Enterprise.

What would IBM think about changing the name of SAFR to GenevaERS Enterprise?

Some pros I can think of are

- Explicitly and at a glance indicates that the commercial version of GenevaERS an extension of the open source GenevaERS.
- Makes the audience for the commercial version more obvious
- Lessens logo / branding changes and allows for more consistency. GenevaERS is the default. Features, documentation, etc... that are only a part of the commercial product would be indicated by using the GenevaERS Enterprise name

An example is https://gradle.org/

**Comment by rhness** [comment]
I support this idea.  I agree with all the advantages you've identified.  Even if the commercial version of the software is named GenevaERS Enterprise, IBM could still use the SAFR name for the service product consisting of the software plus 24/7 support.  

One disadvantage is that if you spell out the product name in full, it becomes the redundantly named Geneva Enterprise Reporting System Enterprise, but the solution is to just never spell it out (except in historical contexts).

**Comment by rhness** [comment]
I've done some web searches now and I'm coming to a slightly different conclusion.  I still like the idea of using GenevaERS as the umbrella term for both the free and paid versions of the software, but I'm now thinking that "Enterprise" may be a bit misleading.  The other products that use this term are trying to make a distinction between a smaller version of the product that is suitable for only personal or departmental usage and a larger Enterprise version that can handle high volumes.  Both the free and paid versions of GenevaERS can handle high volumes, and we want to emphasize the fact that this is our unique feature, so I think we would be better off with another word for the paid version.  What would you think of: 
- Plus
- Premium
- Premier 
- Pro
- Extra
- Advanced
- Advantage 
- Ultimate 
- High-Performance Option 
- Gold
- Platinum

And if we have a distinctive suffix for the paid version, shouldn't we also have a suffix for the free version?  I think we should, just to make clear that whenever we say "GenevaERS" we're referring to the product as a whole and not just the free version.  What do you think of these suffixes? 
- Free
- Basic
- Standard

I'm leaning towards "GenevaERS Standard" and "GenevaERS Premium".  "Free" sounds more appropriate for PC software to me, whereas "Basic" hides the fact that this is still a very powerful tool.  "Standard" doesn't seem to me to have any negative connotations.  

Another alternative would be "GenevaERS (Standard Edition)" and "GenevaERS (Premium Edition)".

**Comment by rhness** [comment]
If a vendor wants to highlight its brand, it may want to call its version something like "GenevaERS (IBM Premium Edition)".  This would give us room in the naming convention for multiple vendors to have their own Premium Editions.  

Here is a useful article on the topic of commercial versions of open source software:  

https://en.wikipedia.org/wiki/Open-core_model

**Comment by KipTwitchell** [comment]
Name remains SAFR due to complexity in changing.
