### ISSUE TITLE
Documentation Approach

### ISSUE THREAD

**Issue by KipTwitchell** [genevaers/community#98]
It is proposed that we consider use of Gatsby as the documentation tooling for web presentation.  To be discussed at the TSC meeting in Feb.

Discussion should be had on User's Guide, Reference, Developer Guide, Impact, Design, etc.  

Additional discussion to be held on DITA vs. MD as well.

**Comment by KipTwitchell** [comment]
TSC meeting discussion: question to Ian as to what the production ready process rather than if this is a prototype effort at this point.

**Comment by SaPeresi** [comment]
Ian would like to demo the website.

**Comment by AOrthVector** [comment]
Here's the link to the artwork created by OPM
https://github.com/openmainframeproject/artwork/tree/main/projects/genevaers

They are in the standard formats including svg

**Comment by SaPeresi** [comment]
discussed creating more data for orders to show large amount.

**Comment by KipTwitchell** [comment]
Looking for push of Gatsby pieces by the May 1st meeting.  MIT license question about acknowledgment, Kip to Investigate that need.

**Comment by KipTwitchell** [comment]
Can this issue be close?

**Comment by emorrow38** [comment]
Yes, we  can close this issue.  Gatsby is most definitely the tool for our main documentation site the "GenevaERS General Documentation" website.  The advantages are:
1.  It's free.
2.  It handles 1000+ topics very well - there are two navigation sidebars on the screen.  The left sidebar allows users to find a topic anywhere in the tree.  The right sidebar allows navigation inside a topic if there are a lot of headings in the topic.

So this issue can be closed.
